[package]
name = "fleetspeak"
version = "0.1.0"
license = "MIT"
authors = ["Łukasz Hanuszczak <hanuszczak@google.com>"]
edition = "2018"

[dependencies]
byteorder = { version = "1.3.4" }
fleetspeak-proto = { path = "proto/" }
prost = { version = "0.6.1" }
prost-types = { version = "0.6.1" }
